// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk57XTFZs1FVCCyeypW7FE7BSLhgPtfZM',
    appId: '1:692702509698:web:1134a674891a7af906129b',
    messagingSenderId: '692702509698',
    projectId: 'ocr-vis-4b00a',
    authDomain: 'ocr-vis-4b00a.firebaseapp.com',
    storageBucket: 'ocr-vis-4b00a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb-cISApy5PkmbRLMj3jo9RCth9vzM5OI',
    appId: '1:692702509698:android:011b302c1c897f6806129b',
    messagingSenderId: '692702509698',
    projectId: 'ocr-vis-4b00a',
    storageBucket: 'ocr-vis-4b00a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf5EfmA72JjLaNTabPJBsmoJiT4wL5XGA',
    appId: '1:692702509698:ios:9cdbdb6ea4a2fbaf06129b',
    messagingSenderId: '692702509698',
    projectId: 'ocr-vis-4b00a',
    storageBucket: 'ocr-vis-4b00a.appspot.com',
    iosClientId: '692702509698-v4k78k1gnvdbkfo9luulc63cdd4o54jn.apps.googleusercontent.com',
    iosBundleId: 'com.example.vehicleReporting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf5EfmA72JjLaNTabPJBsmoJiT4wL5XGA',
    appId: '1:692702509698:ios:9cdbdb6ea4a2fbaf06129b',
    messagingSenderId: '692702509698',
    projectId: 'ocr-vis-4b00a',
    storageBucket: 'ocr-vis-4b00a.appspot.com',
    iosClientId: '692702509698-v4k78k1gnvdbkfo9luulc63cdd4o54jn.apps.googleusercontent.com',
    iosBundleId: 'com.example.vehicleReporting',
  );
}
